language: node_js
node_js:
  - "13"
  - "12"
  - "10"
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
script:
  - yarn test:ci
  # Build the website in PRs so we make sure that PRs do not break the website
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_NODE_VERSION" = "10" ]; then yarn build:website; fi

before_deploy: yarn build:website
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_DEPLOY_TOKEN
  local_dir: website/dist
  on:
    branch: master
    node: "12"
