[build]
command = "yarn build"
#ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ../react-docgen/"
ignore = "if [ -z \"$CACHED_COMMIT_REF\" ] then git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ../../yarn.lock; fi"
publish = ".next"

[environment]
AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
